version: '3.9'

services:

  backend:
    build:
      context: ./backend
    networks:
      - what_net
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    networks:
      - what_net
    ports:
      - "3000:3000"

networks:
  what_net:
